# -*- coding: utf-8 -*-
"""Project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c_7mv02J3mC-VpVHBJAHNZPLXzATx0xW

CAP4630 Project By Steven Pierre

CAR DAMAGE SEVERITY A.I
"""

# Commented out IPython magic to ensure Python compatibility.
#imports section

import sys
import os

if os.getcwd() not in sys.path:
    sys.path.append(os.getcwd())

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
import cv2
import importlib

try:
    import config
    import data_loader
    import severity_scorer
    import models
    import evaluate
    import predict

    # Force reload for changes
    importlib.reload(config)
    importlib.reload(data_loader)
    importlib.reload(severity_scorer)
    importlib.reload(models)
    importlib.reload(evaluate)
    importlib.reload(predict)
except Exception as e:
    print(f"Note: {e}. If files aren't written yet, this is expected.")

# inline plts
# %matplotlib inline

#config.py
import os
import numpy as np

BASE_DIR = os.path.dirname(os.path.abspath('__file__'))
DATA_CSV = os.path.join(BASE_DIR, "data.csv")
IMAGE_DIR = os.path.join(BASE_DIR, "Image")
OUTPUT_DIR = os.path.join(BASE_DIR, "outputs")
MODEL_DIR = os.path.join(OUTPUT_DIR, "Models")
PLOT_DIR = os.path.join(OUTPUT_DIR, "Plots")

os.makedirs(MODEL_DIR, exist_ok=True)
os.makedirs(PLOT_DIR, exist_ok=True)

IMG_SIZE = (224, 224)
IMG_CHANNELS = 3

TEST_SIZE = 0.2
VAL_SIZE = 0.15
RANDOM_STATE = 42

DL_EPOCHS = 20
DL_BATCH_SIZE = 32
DL_LR = 1e-4
DL_DROPOUT = 0.40
FINE_TUNE_AT = 100

CLASS_LABELS = [
    "unknown",
    "Bumper_Scratch",
    "Door_Scratch",
    "Bumper_Dent",
    "Door_Dent",
    "Head lamp",
    "Tail lamp",
    "Glass Shatter",
]

NUM_CLASSES = len(CLASS_LABELS)

BASE_SEVERITY = {
    "unknown": 1,
    "Bumper_Scratch": 2,
    "Door_Scratch": 2,
    "Bumper_Dent": 3,
    "Door_Dent": 3,
    "Head lamp": 4,
    "Tail lamp": 4,
    "Glass Shatter": 5,
}

SEVERITY_DESCRIPTIONS = {
    1: "Unknown - No significant damages were detected",
    2: "Low - cosmetic damage, no structural",
    3: "Medium - structural damage present; repairs advised",
    4: "High - safety concerns, component damgages, urget repairs needed",
    5: "Critical - immediate repairs needed, vehicle cannot be driven for safety concerns",
}

SEVERITY_COLORS = {
    1: "Grey",
    2: "orange",
    3: "red",
    4: "purple",
    5: "black",
}

HOG_ORIENTATIONS = 9
HOG_PIXELS_PER_CELL = 16
HOG_CELLS_PER_BLOCK = 2

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/Project/config.py
# import os
# import numpy as np
# 
# BASE_DIR = '/content/Project'
# DATA_CSV = os.path.join(BASE_DIR, "data.csv")
# IMAGE_DIR = "/content/Image"
# OUTPUT_DIR = os.path.join(BASE_DIR, "outputs")
# MODEL_DIR = os.path.join(OUTPUT_DIR, "Models")
# PLOT_DIR = os.path.join(OUTPUT_DIR, "Plots")
# 
# os.makedirs(MODEL_DIR, exist_ok=True)
# os.makedirs(PLOT_DIR, exist_ok=True)
# 
# IMG_SIZE = (224, 224)
# IMG_CHANNELS = 3
# 
# TEST_SIZE = 0.2
# VAL_SIZE = 0.15
# RANDOM_STATE = 42
# 
# DL_EPOCHS = 20
# DL_BATCH_SIZE = 32
# DL_LR = 1e-4
# DL_DROPOUT = 0.40
# FINE_TUNE_AT = 100
# 
# CLASS_LABELS = [
#     "unknown",
#     "bumper_scratch",
#     "door_scratch",
#     "bumper_dent",
#     "door_dent",
#     "head_lamp",
#     "tail_lamp",
#     "glass_shatter",
# ]
# 
# NUM_CLASSES = len(CLASS_LABELS)
# 
# BASE_SEVERITY = {
#     "unknown": 1,
#     "bumper_scratch": 2,
#     "door_scratch": 2,
#     "bumper_dent": 3,
#     "door_dent": 3,
#     "head lamp": 4,
#     "head_lamp": 4,
#     "tail lamp": 4,
#     "tail_lamp": 4,
#     "glass shatter": 5,
#     "glass_shatter": 5,
# }
# 
# SEVERITY_DESCRIPTIONS = {
#     1: "Unknown - No significant damages were detected",
#     2: "Low - cosmetic damage, no structural",
#     3: "Medium - structural damage present; repairs advised",
#     4: "High - safety concerns, component damgages, urget repairs needed",
#     5: "Critical - immediate repairs needed, vehicle cannot be driven for safety concerns",
# }
# 
# HOG_ORIENTATIONS = 9
# HOG_PIXELS_PER_CELL = (16, 16)
# HOG_CELLS_PER_BLOCK = (2, 2)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/Project/data_loader.py
# import config
# import os
# import numpy as np
# import pandas as pd
# import cv2
# from PIL import Image
# from skimage.feature import hog
# from sklearn.preprocessing import LabelEncoder
# from sklearn.model_selection import train_test_split
# from tqdm import tqdm
# 
# def load_image_pil(path: str):
#     try:
#         return Image.open(path).convert("RGB")
#     except Exception:
#         return None
# 
# def preprocess_image(img: Image.Image, size=config.IMG_SIZE) -> np.ndarray:
#     img = img.convert("RGB")
#     img = img.resize((size[1], size[0]))
#     return np.array(img, dtype=np.float32) / 255.0
# 
# def extract_features(img_array: np.ndarray) -> np.ndarray:
#     gray = cv2.cvtColor((img_array * 255).astype(np.uint8), cv2.COLOR_RGB2GRAY)
#     return hog(
#         gray,
#         orientations=config.HOG_ORIENTATIONS,
#         pixels_per_cell=config.HOG_PIXELS_PER_CELL,
#         cells_per_block=config.HOG_CELLS_PER_BLOCK,
#         feature_vector=True,
#     )
# 
# def extract_color_histogram(img_array: np.ndarray, bins: int = 32) -> np.ndarray:
#     hists = []
#     for ch in range(3):
#         h, _ = np.histogram(img_array[:, :, ch] * 255, bins=bins, range=(0, 256))
#         hists.append(h.astype(np.float32) / (h.sum() + 1e-8))
#     return np.concatenate(hists)
# 
# def extract_combined_features(img_array: np.ndarray) -> np.ndarray:
#     return np.concatenate([
#         extract_features(img_array),
#         extract_color_histogram(img_array),
#     ])
# 
# class VehicleDamageDataset:
#     def __init__(self, csv_file: str = config.DATA_CSV, image_dir: str = config.IMAGE_DIR):
#         self.csv_file = csv_file
#         self.image_dir = image_dir
#         self.df = None
#         self.images = []
#         self.labels = []
#         self.le = LabelEncoder()
#         self.loaded = False
# 
#     def load(self, skip_unknown: bool = False):
#         self.df = pd.read_csv(self.csv_file)
#         cols = {c.lower().strip(): c for c in self.df.columns}
#         img_col = cols.get("image_id") or cols.get("image") or cols.get("filename")
#         lbl_col = cols.get("classes") or cols.get("class") or cols.get("label")
# 
#         if skip_unknown:
#             self.df = self.df[self.df[lbl_col].astype(str).str.lower().str.strip() != "unknown"].reset_index(drop=True)
# 
#         images, labels = [], []
#         print(f"DEBUG: Starting load from {self.image_dir}")
#         for i, row in tqdm(self.df.iterrows(), total=len(self.df), desc="Loading"):
#             img_path = os.path.join(self.image_dir, os.path.basename(str(row[img_col])))
#             if i < 3: # Debug: print first 3 paths
#                 print(f"DEBUG: Inspecting path -> {img_path}")
#                 print(f"DEBUG: File exists? -> {os.path.exists(img_path)}")
# 
#             img = load_image_pil(img_path)
#             if img is not None:
#                 images.append(preprocess_image(img))
#                 labels.append(str(row[lbl_col]).strip())
# 
#         if len(images) == 0:
#             raise ValueError(f"No images loaded from {self.image_dir}. Check paths and CSV content.")
# 
#         self.images, self.labels = np.array(images, dtype=np.float32), np.array(labels)
#         self.le.fit(self.labels)
#         self.loaded = True
#         return self
# 
#     def get_classical_splits(self):
#         print("Extracting features...")
#         X = np.array([extract_combined_features(img) for img in tqdm(self.images)])
#         y = self.le.transform(self.labels)
# 
#         if len(X) < 2:
#             raise ValueError("Not enough samples to split into train and test sets.")
# 
#         splits = train_test_split(X, y, test_size=config.TEST_SIZE, random_state=config.RANDOM_STATE, stratify=y)
#         return list(splits) + [self.le]

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/Project/severity_scorer.py
# import config
# import numpy as np
# 
# CONF_WEIGHT = 0.5
# 
# def compute_severity(predicted_class: str, confidence: float) -> dict:
#   lookup_key = str(predicted_class).lower().strip()
#   base = config.BASE_SEVERITY.get(lookup_key, 1)
#   shift = (confidence - 0.50) * CONF_WEIGHT
#   adjusted = base + shift
#   severity_score = int(np.clip(round(adjusted), 1, 5))
#   return {
#       "severity_score": severity_score,
#       "severity_label": config.SEVERITY_DESCRIPTIONS[severity_score],
#       "base_score": base,
#       "confidence": round(float(confidence), 4),
#       "predicted_class": predicted_class
#   }
# 
# def print_severity_report(result: dict) -> None:
#   bar = "#" * result["severity_score"] + "-" * (5 - result["severity_score"])
#   print(f"\nSeverity: {result['severity_score']}/5 [{bar}]")
#   print(f"Class: {result['predicted_class']} | Assessment: {result['severity_label']}\n")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/Project/models.py
# import config
# from sklearn.ensemble import RandomForestClassifier, VotingClassifier, HistGradientBoostingClassifier
# from sklearn.svm import SVC
# from sklearn.pipeline import make_pipeline
# from sklearn.preprocessing import StandardScaler
# 
# def build_ensemble():
#     estimators = [
#         ("rf", RandomForestClassifier(n_estimators=50, random_state=config.RANDOM_STATE)),
#         ("svm", make_pipeline(StandardScaler(), SVC(probability=True, random_state=config.RANDOM_STATE))),
#         ("gb", HistGradientBoostingClassifier(max_iter=20, random_state=config.RANDOM_STATE))
#     ]
#     return VotingClassifier(estimators, voting="soft")
# 
# CLASSICAL_MODELS = {"Soft-Voting Ensemble": build_ensemble()}

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/Project/evaluate.py
# import config
# import os
# import matplotlib.pyplot as plt
# from sklearn.metrics import accuracy_score
# 
# def evaluate_classifier(y_true, y_pred, le, name="Model"):
#     acc = accuracy_score(y_true, y_pred)
#     print(f"[{name}] Accuracy: {acc*100:.2f}%")
#     return {"Accuracy": acc}

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/Project/train.py
# import os
# import joblib
# import config
# from data_loader import VehicleDamageDataset
# import evaluate as ev
# from models import CLASSICAL_MODELS
# 
# def train_classical(skip_unknown: bool):
#     ds = VehicleDamageDataset().load(skip_unknown=skip_unknown)
#     X_tr, X_te, y_tr, y_te, le = ds.get_classical_splits()
#     joblib.dump(le, os.path.join(config.MODEL_DIR, 'label_encoder.pkl'))
# 
#     print(f'\nTraining Classical Models (skip_unknown={skip_unknown})...')
#     for name, model in CLASSICAL_MODELS.items():
#         print(f'  Fitting {name}...')
#         model.fit(X_tr, y_tr)
#         y_pred = model.predict(X_te)
#         ev.evaluate_classifier(y_te, y_pred, le, name)
#         joblib.dump(model, os.path.join(config.MODEL_DIR, 'best_classical_model.pkl'))
#     print('Training complete.')
# 
# if __name__ == '__main__':
#     train_classical(skip_unknown=True)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/Project/predict.py
# import config
# import os
# import joblib
# import numpy as np
# import matplotlib.pyplot as plt
# from PIL import Image
# from data_loader import load_image_pil, preprocess_image, extract_combined_features
# from severity_scorer import compute_severity
# 
# def load_model():
#     m_path = os.path.join(config.MODEL_DIR, "best_classical_model.pkl")
#     l_path = os.path.join(config.MODEL_DIR, "label_encoder.pkl")
#     if not os.path.exists(m_path): return None, None
#     return joblib.load(m_path), joblib.load(l_path)
# 
# def predict_image(path, model, le):
#     img = load_image_pil(path)
#     if img is None: return {"error": "bad image"}
#     x = preprocess_image(img)
#     p = model.predict_proba(extract_combined_features(x).reshape(1, -1))[0]
#     idx = int(np.argmax(p))
#     return compute_severity(le.inverse_transform([idx])[0], float(p[idx]))

import sys
import os
import shutil

# 1. Fix Image Directory Structure
if not os.path.exists('/content/Image'):
    os.makedirs('/content/Image')

# Move images from /content to /content/Image if they exist there
for f in os.listdir('/content'):
    if f.endswith('.jpeg') or f.endswith('.jpg') or f.endswith('.png'):
        shutil.move(os.path.join('/content', f), os.path.join('/content/Image', f))

# 2. Setup Project Environment
PROJECT_ROOT = '/content/Project'
os.chdir(PROJECT_ROOT)
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

# Clear cache to ensure we use updated code
modules_to_clear = ['config', 'data_loader', 'severity_scorer', 'models', 'evaluate', 'train', 'predict']
for mod in list(sys.modules.keys()):
    if mod in modules_to_clear:
        del sys.modules[mod]

try:
    import train
    import config

    print(f'--- Starting Path Verification and Training ---')
    print(f'Working Directory: {os.getcwd()}')
    print(f'Looking for images in: {config.IMAGE_DIR}')

    # Run training
    train.train_classical(skip_unknown=True)

except Exception as e:
    print(f'Execution error: {e}')
    import traceback
    traceback.print_exc()
finally:
    os.chdir('/content')

pip install numpy pandas pillow opencv-python scikit-learn scikit-image tqdm matplotlib seaborn joblib tensorflow

!python /content/Project/train.py --mode deep

!ls -R /content

from Project import config, predict, severity_scorer
import importlib
import pandas as pd
import os

# Reloading all modules to ensure the lowercase mapping and scorer logic are applied
importlib.reload(config)
importlib.reload(severity_scorer)
importlib.reload(predict)

def run_random_demo(n=5):
    """Modified demo runner that uses a random seed for different images each time"""
    if not os.path.exists(config.DATA_CSV):
        print(f"CSV not found at {config.DATA_CSV}")
        return

    df = pd.read_csv(config.DATA_CSV)
    model, le = predict.load_model()
    if model is None:
        print("Model not found. Run training first.")
        return

    cols = {c.lower().strip(): c for c in df.columns}
    lbl_col = cols.get("classes") or cols.get("class") or cols.get("label")

    # filter and sample with random_state=None for variety
    demo_df = df[df[lbl_col].astype(str).str.lower() != "unknown"]
    demo_df = demo_df.sample(n=min(n, len(demo_df)), random_state=None)

    for _, r in demo_df.iterrows():
        path = os.path.join(config.IMAGE_DIR, os.path.basename(str(r[cols.get("image_id") or cols.get("image") or cols.get("filename")])))
        res = predict.predict_image(path, model, le)
        if "error" in res:
            continue

        severity_scorer.print_severity_report(res)
        predict.plt.figure(figsize=(6, 4))
        predict.plt.imshow(predict.Image.open(path))
        predict.plt.title(f"True: {r[lbl_col]} | Pred: {res['predicted_class']}")
        predict.plt.axis('off')
        predict.plt.show()

print("Running Random Demo...")
try:
    run_random_demo(n=5)
except Exception as e:
    print(f"Error running demo: {e}")

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
import sys
import importlib

# Clear the module for a fresh import
for module_name in list(sys.modules.keys()):
    if module_name.startswith('Project'):
        del sys.modules[module_name]

# Now, directly imports the needed submodules
import Project.config as config
import Project.predict as predict
import Project.severity_scorer as severity_scorer

# Reload
importlib.reload(config)
importlib.reload(predict)
importlib.reload(severity_scorer)

def run_enhanced_demo(n=3):
    # font settings, personal change
    plt.rcParams["font.family"] = "serif"
    plt.rcParams["font.serif"] = ["Times New Roman"] + plt.rcParams["font.serif"]

    df = pd.read_csv(config.DATA_CSV) #imported config
    cols = {c.lower().strip(): c for c in df.columns}
    img_col = cols.get("image_id") or cols.get("image") or cols.get("filename")
    lbl_col = cols.get("classes") or cols.get("class") or cols.get("label")

    model, le = predict.load_model() # imported predict
    if model is None:
        print("Model not found. Please run training first.")
        return

    # randomize images
    demo_df = df[df[lbl_col].astype(str).str.lower() != "unknown"]
    demo_df = demo_df.sample(n=min(n, len(demo_df)))

    fig, axes = plt.subplots(1, n, figsize=(4 * n, 5)) # width
    if n == 1: axes = [axes]

    for i, (_, row) in enumerate(demo_df.iterrows()):
        path = os.path.join(config.IMAGE_DIR, os.path.basename(str(row[img_col])))
        res = predict.predict_image(path, model, le)

        if "error" in res:
            continue

        score = res["severity_score"]
        # Borders
        if score >= 4: color = 'red'       #critical
        elif score == 3: color = 'yellow'  #moderate
        else: color = 'green'             #minor

        img = Image.open(path)
        axes[i].imshow(img)

        # title bolded
        axes[i].set_title(f"Pred: {res['predicted_class']}\nScore: \\mathbf{{{score}}}/5", fontsize=14)

        # colored border
        for spine in axes[i].spines.values():
            spine.set_edgecolor(color)
            spine.set_linewidth(5)
            spine.set_visible(True)

        axes[i].set_xticks([])
        axes[i].set_yticks([])

    plt.tight_layout()
    plt.subplots_adjust(wspace=0.3, hspace=0.3) # subplots spacing for readbility

    # Save results
    save_path = os.path.join(config.PLOT_DIR, "demo_results.png")
    plt.savefig(save_path)
    print(f"Demo plot saved to: {save_path}")
    plt.show()

# Run demo
run_enhanced_demo(n=5)

run_enhanced_demo(n=10)

"""Red = score 4 or 5 (critical)

Yellow border = score 3 (moderate)

Green border = score 1 or 2 (minor)
"""